/** Opciones del cotizador alineadas al formulario original (Wix). */

export type CotizadorSelectEntry =
  | { kind: 'option'; value: string; label: string }
  | { kind: 'separator' };

export const COTIZADOR_MODEL_ENTRIES: CotizadorSelectEntry[] = [
  { kind: 'option', value: 'Scooter', label: 'Scooter' },
  { kind: 'option', value: 'RayZR', label: 'RayZR' },
  { kind: 'option', value: 'XMax300', label: 'XMax300' },
  { kind: 'separator' },
  { kind: 'option', value: 'Sport', label: 'Sport' },
  { kind: 'option', value: 'Crux Rev', label: 'Crux Rev' },
  { kind: 'option', value: 'YBR125ED', label: 'YBR125ED' },
  { kind: 'option', value: 'YBR125G', label: 'YBR125G' },
  { kind: 'option', value: 'SZ150RR', label: 'SZ150RR' },
  { kind: 'option', value: 'FZ150 FI', label: 'FZ150 FI' },
  { kind: 'option', value: 'FZ150-S FI', label: 'FZ150-S FI' },
  { kind: 'option', value: 'FZ150 v3.0 FI ABS', label: 'FZ150 v3.0 FI ABS' },
  { kind: 'option', value: 'FZ250 FI', label: 'FZ250 FI' },
  { kind: 'option', value: 'MT03 ABS', label: 'MT03 ABS' },
  { kind: 'separator' },
  { kind: 'option', value: 'Montañeras', label: 'Montañeras' },
  { kind: 'option', value: 'XTZ125', label: 'XTZ125' },
  { kind: 'option', value: 'XTZ150 FI', label: 'XTZ150 FI' },
  { kind: 'option', value: 'XT250 FI', label: 'XT250 FI' },
  { kind: 'option', value: 'TÉNÉRÉ 700', label: 'TÉNÉRÉ 700' },
  { kind: 'separator' },
  { kind: 'option', value: 'Alta Cilindrada', label: 'Alta Cilindrada' },
  { kind: 'option', value: 'MT-03 FI', label: 'MT-03 FI' },
  { kind: 'option', value: 'MT-07 FI', label: 'MT-07 FI' },
  { kind: 'option', value: 'MT-09 FI', label: 'MT-09 FI' },
  { kind: 'option', value: 'MT-09 SP FI', label: 'MT-09 SP FI' },
  { kind: 'option', value: 'Tracer 9 GT FI', label: 'Tracer 9 GT FI' },
  { kind: 'option', value: 'R3 FI', label: 'R3 FI' },
  { kind: 'option', value: 'R7 FI', label: 'R7 FI' },
  { kind: 'option', value: 'R1 FI', label: 'R1 FI' },
  { kind: 'option', value: 'R1 M', label: 'R1 M' },
  { kind: 'separator' },
  { kind: 'option', value: 'Motocross / Enduro', label: 'Motocross / Enduro' },
  { kind: 'option', value: 'YZ65', label: 'YZ65' },
  { kind: 'option', value: 'YZ125', label: 'YZ125' },
  { kind: 'option', value: 'YZ250', label: 'YZ250' },
  { kind: 'option', value: 'YZ250F', label: 'YZ250F' },
  { kind: 'option', value: 'YZ450F', label: 'YZ450F' },
  { kind: 'option', value: 'WR250F', label: 'WR250F' },
  { kind: 'option', value: 'WR450F', label: 'WR450F' },
  { kind: 'separator' },
  { kind: 'option', value: 'Cuadraciclos', label: 'Cuadraciclos' },
  { kind: 'option', value: 'Grizzly 350 4x2', label: 'Grizzly 350 4x2' },
  { kind: 'option', value: 'Kodiak 450 4x4', label: 'Kodiak 450 4x4' },
  { kind: 'option', value: 'Grizzly 700 4x4 XTR', label: 'Grizzly 700 4x4 XTR' },
  { kind: 'option', value: 'Raptor 90', label: 'Raptor 90' },
  { kind: 'option', value: 'Raptor 700 SE', label: 'Raptor 700 SE' },
  { kind: 'option', value: 'YFZ450R', label: 'YFZ450R' },
  { kind: 'separator' },
  { kind: 'option', value: 'Mulas', label: 'Mulas' },
  { kind: 'option', value: 'Viking EPS 6p', label: 'Viking EPS 6p' },
  { kind: 'option', value: 'Wolverine X4 850', label: 'Wolverine X4 850' },
  { kind: 'option', value: 'RMax1000 X4', label: 'RMax1000 X4' },
  { kind: 'separator' },
  { kind: 'option', value: 'Motor Fuera de Borda', label: 'Motor Fuera de Borda' },
];

export const COTIZADOR_BRANCH_OPTIONS: { value: string; label: string }[] = [
  { value: 'Alajuela', label: 'Alajuela' },
  { value: 'Heredia', label: 'Heredia' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'San Carlos', label: 'San Carlos' },
  { value: 'San Ramón', label: 'San Ramón' },
  { value: 'Plaza Viquez', label: 'Plaza Viquez' },
  { value: 'Quepos', label: 'Quepos' },
  { value: 'Uruca', label: 'Uruca' },
];
